spring.application.name=api-produtos

#SERVIDOR
server.port=8181

#BANCO DE DADOS H2
spring.datasource.url=jdbc:h2:mem:produtosdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#JPA/HIBERNATE
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#CONSOLE DO H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#SWAGGER / OPENAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.path=/swagger-ui.html

#JWT
api-settings.secret=uma-chave-secreta-muito-longa-para-hmac-sha256-que-tem-32-bytes-de-comprimento
api-settings.issuer=meudominio.com
api-settings.audience=meudominio.com
api-settings.access-token-expiry-minutes=60

#Cors
app.cors.allowed-origins=http://localhost:8181,http://localhost:3000,http://localhost:4200


